### ISSUE TITLE
Add ability to register and manage namespaces from the web UI

### ISSUE THREAD

**Issue by kelnos** [temporalio/web#127]
We'd really like to be able to manage namespaces from the web UI.  Our production systems are fairly locked down such that, even on our production VPN, developers can't just run `tctl` from their laptop and be able to get to the cluster.  As we're deploying this internally as a shared service that will be used by multiple teams, most people will also not be able to ssh into the temporal hosts in order to run `tctl` locally.

Being able to do this from the web UI, which we do make available to internal employees who are on our production VPN, would make things a lot easier for our internal onboarding.

**Comment by feedmeapples** [comment]
@kelnos thanks for filing this!
We plan to add this feature after v1. As for v1 the focus is on stabilization and essential web improvements

**Comment by sw-yx** [comment]
leaving this open - no timeline on doing this yet but its certainly something we want.
