### ISSUE TITLE
[Feature Request] Add link to report bugs/feature requests

### ISSUE THREAD

**Issue by sw-yx** [temporalio/web#200]
**Is your feature request related to a problem? Please describe.**

people dont have a good reminder of where to report temporal web bugs/feature requests inside of temporal web.

**Describe the solution you'd like**

let's provide a link to our github issue creator https://github.com/temporalio/web/issues/new/choose

no opinion on where to add it, lets see what you come up with

**Comment by sw-yx** [comment]
![feebdack](https://user-images.githubusercontent.com/6764957/99364631-28b34a00-28f1-11eb-9252-c4143d8d01fb.gif)

interesting concept we can steal

**Comment by feedmeapples** [comment]
closing this issue as #211 addresses it
