### ISSUE TITLE
[Bug] Workflow list shows nothing (but it should)

### ISSUE THREAD

**Issue by SimonKO9** [temporalio/web#207]
**Describe the bug**
It seems that there's a bug in code that prevents loading workflows. It is happening when listing status=ALL.
What's interesting, I can see workflows when inspecting JSON responses.

```
workflow-list.vue:335 Uncaught (in promise) TypeError: startTime.add is not a function
    at _callee$ (workflow-list.vue:335)
    at tryCatch (runtime.js:65)
    at Generator.invoke [as _invoke] (runtime.js:303)
    at Generator.prototype.<computed> [as next] (runtime.js:117)
    at asyncGeneratorStep (workflow-list.vue:86)
    at _next (workflow-list.vue:86)
```

**To Reproduce**
1. Go to 'workflow list'
2. No workflows appear although there are some running

**Expected behavior**
I expected to see workflows.

**Screenshots**
![image](https://user-images.githubusercontent.com/8093292/99953749-03578d80-2d82-11eb-9383-3db225d81731.png)

**Desktop (please complete the following information where relevant):**
 - MacOS
 - Brave
 - Docker ps:
```
➜  ~ docker ps
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS              PORTS                                                                      NAMES
d7d76f99a811        temporalio/admin-tools:1.3.0   "tail -f /dev/null"      25 minutes ago      Up 25 minutes                                                                                  compose_temporal-admin-tools_1
ccfe46fd1e0d        temporalio/web:1.3.0           "docker-entrypoint.s…"   25 minutes ago      Up 25 minutes       0.0.0.0:8088->8088/tcp                                                     compose_temporal-web_1
60391f5f7929        temporalio/auto-setup:1.3.0    "/docker-entrypoint.…"   25 minutes ago      Up 25 minutes       6933-6935/tcp, 6939/tcp, 7234-7235/tcp, 7239/tcp, 0.0.0.0:7233->7233/tcp   compose_temporal_1
67ee058fe1a5        postgres:9.6                   "docker-entrypoint.s…"   25 minutes ago      Up 25 minutes       0.0.0.0:5432->5432/tcp                                                     compose_postgresql_1
```

**Additional context**
It seems to start happening when one of the running workflows throws an exception.

**Comment by sev3ryn** [comment]
same for me

Another interesting thing is that workflows are not visible only if one of them is in running state. If all are completed - workflow list displays ok

**Comment by feedmeapples** [comment]
The issue itself is fixed locally. I'm adding unit tests for the `all` workflows view. The fix should be released asap as a patch
