### ISSUE TITLE
[Feature Request] Cancelling a workflow

### ISSUE THREAD

**Issue by MrSaints** [temporalio/web#210]
**Is your feature request related to a problem? Please describe.**

It is currently possible to terminate a workflow from the web UI.

But a termination is similar to a hard `kill -9`. In some cases, a graceful cancel is preferred so that clean up activities can execute.

**Describe the solution you'd like**

![2020-11-25-204525_395x179_scrot](https://user-images.githubusercontent.com/68859/100279831-2a1eeb00-2f5f-11eb-85ff-beb38c384a3f.png)

An additional action to cancel a workflow.

**Additional context**

Understandably, this can already be done through `tctl`, but for convenience (and not having to set-up or have direct cluster access), it would be nice to have this feature on the web UI.

**Comment by sw-yx** [comment]
thanks for filing! it's something we want to do in the future, but for now Temporal Web is view-only. Keep a look out for "Temporal Web 2.0" where we'll do all this control plane stuff
