### ISSUE TITLE
Child workflow links on web UI do not work

### ISSUE THREAD

**Issue by skrul** [temporalio/web#218]
## Expected Behavior

When viewing a workflow's history in the Temporal Web UI, the `ChildWorkflowExecutionStarted` task has the child workflow's run id as a link. Clicking this link should allow you to view the child workflow's history.

## Actual Behavior

Link just brings you back to the workflow search results.

## Steps to Reproduce the Problem

1. View a workflow's history that runs child workflows.
2. Click the linked run id of a child workflow.

## Specifications

  - Version: temporal web v1.3.0

**Comment by feedmeapples** [comment]
@skrul tried the repro steps and haven't reproed the issue, clicking the RunId navigated to the child workflow page successfully.
Could you provide more details:
 - what is the execution statuses of parent and child workflows? (running, completed..)
 - what is the setup you are running on? Is ES enabled?
 - does the link contain both workflow id and run id in the path and then link ends by summary? like here:
![image](https://user-images.githubusercontent.com/11838981/101562226-da3b1d80-397b-11eb-9fc4-86764f01a755.png)

**Comment by feedmeapples** [comment]
@skrul pls lmk if you are still seeing this issue, especially on newer versions of web. If yes, please provide more details on repro (see questions above). Closing as no repro
