### ISSUE TITLE
[Bug] Auth does not work well in chrome Version 87.0.4280.88 (Official Build) (64-bit)

### ISSUE THREAD

**Issue by kkcmadhu** [temporalio/web#221]
**Describe the bug**
When Auth is configured with keycloak and accessed through chrome, script error occurs
"Uncaught (in promise) NavigationDuplicated: Avoided redundant navigation to current location: "/signin".
    at createRouterError (http://localhost:8088/temporal.3bd23fc1fe6efde1af06.js:109604:15)"

**To Reproduce**
1. Configure Auth  with keycloak
2. Click on 'signon with sso"
3. error occurs
**Expected behavior**
Dashboard should be displayed.

**Screenshots**

![image](https://user-images.githubusercontent.com/997582/101618385-ef758200-3a37-11eb-9c47-1cba45c533c8.png)

**Desktop (please complete the following information where relevant):**
 - OS: Windows 10
 - Browser chome
 - Temporal Web Version 1.40web
 - are you using Docker or building from source? Docker

**Additional context**
Works just fine in Edge Version 87.0.664.57 (Official build) (64-bit)

**Comment by sw-yx** [comment]
@feedmeapples this looks familiar. i thought we fixed it!

**Comment by feedmeapples** [comment]
@sw-yx the initial keycloak auth issue was fixed. In the above `NavigationDuplicated` error is not exactly something specific to keycloak. Vue-router contributors suggest to just skip it https://stackoverflow.com/a/58747480
 
@kkcmadhu Could you provide more details:
 - does the authentication succeed?
 - if not, could you provide the details of the steps to repro the issue? Especially whether you are being navigated to keycloak to provide the credentials, or the issue happens before that?
 - are you using Web app or Single Page app config in Keycloak?

**Comment by kkcmadhu** [comment]
yes authentication succeeds, as far as keycloak is concerned there is no web page/signe page app config (like okta)
i just created a clientid/client secret ( of type confidential)  in keycloak.
And as i mentioned this was happening in chrome alone, the same setting works perfectly fine in edge/firefox.

**Comment by feedmeapples** [comment]
@kkcmadhu sorry for the delayed follow up. As i understand, since the auth succeeds you are able to use the Authn feature right? Then the issue itself is filed because of the error log in console saying "navigation duplicated" ? 
If so, this error message is expected and it doesn't have any impact on the app. I'm thinking to hide this error, as suggested by vuejs contributor Posva https://stackoverflow.com/a/58747480

**Comment by kkcmadhu** [comment]
Yup. This is not an issue, infact I think clearing cookies solved most of the issues and I was not able to reproduce this consistently. Please close this issue.

Sent from Yahoo Mail on Android 
 
  On Fri, 8 Jan 2021 at 1:34 pm, Ruslan<notifications@github.com> wrote:   


@kkcmadhu sorry for the delayed follow up. As i understand, since the auth succeeds you are able to use the Authn feature right? Then the issue itself is filed because of the error log in console saying "navigation duplicated" ?
If so, this error message is expected and it doesn't have any impact on the app. I'm thinking to hide this error, as suggested by vuejs contributor Posva https://stackoverflow.com/a/58747480

**Comment by feedmeapples** [comment]
sg
