### ISSUE TITLE
[Bug] 2nd+ clicks in the workflow graph do not navigate to the relevant event

### ISSUE THREAD

**Issue by GreyTeardrop** [temporalio/web#235]
**Describe the bug**
The first time user clicks any event in the event graph on the workflow history page, she is navigated to the relevant event in the event list. However, any subsequent clicks on the same graph would not trigger navigation anymore. Refreshing the graph by either navigating to the workflow summary view or to the workflow list allows one to repeat again: the next click would navigate to the event but subsequent clients do nothing.

**To Reproduce**
1. Go to the workflow history page
2. Click "show graph"
3. Click any event on that graph
4. See that the event list below is scrolled down to the relevant event
5. Click any other event on that graph
6. See that no navigation happens now

**Expected behavior**
Any click in the history graph would navigate the user to the relevant event in the event list below.

**Screenshots**
See the screencast for an example
![](https://user-images.githubusercontent.com/61568/103167912-db06f700-4837-11eb-9c65-782f607eb034.gif)
https://user-images.githubusercontent.com/61568/103167640-882c4000-4835-11eb-9573-00ccfdb178bd.mp4

**Desktop (please complete the following information where relevant):**
 - OS: macOS Big Sur 11.1
 - Browsers:
   - Chrome 87.0.4280.88 (Official Build) (x86_64)
   - Firefox 84.0.1 (64-bit)
   - Safari 14.0.2 (16610.3.7.1.9)
 - Temporal Web Version: 1.4.1
 - Tctl Version: 1.5.0
 - Deployed via official `docker-compose.yml`

**Comment by sw-yx** [comment]
still have not made time to repro this :( @GreyTeardrop lmk how critical this is for you

**Comment by GreyTeardrop** [comment]
It's mostly a minor issue that doesn't significantly affect me. I might even say it has more impact on pitching Temporal to other developers :-)

**Comment by GreyTeardrop** [comment]
Hey @sw-yx, do you mind keeping this issue open?

**Comment by GreyTeardrop** [comment]
@sw-yx 🙏

**Comment by GreyTeardrop** [comment]
Hey @sw-yx, looks like this issue was auto-closed. I know it's not a high impact or high priority, but I wonder if it could still be kept open?

**Comment by sw-yx** [comment]
dammit sorry still learning how to deal with github actions
