### ISSUE TITLE
[Feature Request] Reset workflow from GUI

### ISSUE THREAD

**Issue by durango** [temporalio/web#247]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I can't reset an entire workflow through the GUI.

**Describe the solution you'd like**
A button right next to the Terminate button would be fine. Ask for a reason too with a modal popup, etc. Dropdown button group for different `reset_type`s but not totally necessary. 

**Additional context**
GUI interface for this:
`tctl wf rs -w <workflow> --reason <my reason> --reset_type FirstWorkflowTask`

**Comment by sw-yx** [comment]
i like it. tbd on whether or not we dedicate eng resources on this right now (we have prioritized other things at the moment), but if you'd like to take a crack at a PR i'd be happy to review.

**Comment by sw-yx** [comment]
still no timeline on this, sorry.

**Comment by durango** [comment]
I'm in the same boat as you, if/when I find time would be more than happy to help. Just need to find it
