### ISSUE TITLE
[Bug] Exception in stackTrace

### ISSUE THREAD

**Issue by darewreck54** [temporalio/web#250]
**Describe the bug**
When the workflow is running, and I look at the stack trace i get the following 
![image](https://user-images.githubusercontent.com/16171726/105850263-5f16e080-5f96-11eb-8d94-2edf9c697b6f.png)

However, the workflow does complete without any issue seen in the history tab.

**Desktop (please complete the following information where relevant):**
 - OS: [iOS]
 - Browser [chrome]
 - Temporal Web Version [1.31]

**Comment by sw-yx** [comment]
@feedmeapples can you recognize this error?

**Comment by darewreck54** [comment]
I'm still seeing it with 1.7.0 web whenever you click on the `stack trace` tab when the workflow is complete

**Comment by sw-yx** [comment]
thanks @darewreck54  - i have not attempted a repro yet but thanks for the update
