### ISSUE TITLE
[Feature Request] Ability to query the workflow after its completed

### ISSUE THREAD

**Issue by darewreck54** [temporalio/web#251]
**Is your feature request related to a problem? Please describe.**
It's nice to have workflow states that you can query after the workflow is done.  For example, there are internal values that I track in the workflow.  After each activity completes, I want set those values to indicate if state is passed around or the status of each activity.  It would be nice after the workflow is complete, that i'm able to query for those custom fields.

**Describe the solution you'd like**
After the workflow is complete, it would be nice to be able to query the final state of the query parameters.

![image](https://user-images.githubusercontent.com/16171726/106072586-4c4afb80-60bd-11eb-9073-09ca3fd296cb.png)

**Comment by GreyTeardrop** [comment]
I would also love to have this feature implemented at some point
