### ISSUE TITLE
[Feature Request] Add TaskQueue filter to workflows table

### ISSUE THREAD

**Issue by robholland** [temporalio/web#274]
**Is your feature request related to a problem? Please describe.**
Developers will often be working on a specific task queue when needing to see what the current state of play is. Having a task queue filter in the basic query mode would make this a lot easier.

**Describe the solution you'd like**
Task queue filter alongside the current WorkflowId, WorkflowName and WorkflowStatus filters.

**Additional context**

**Comment by sw-yx** [comment]
@feedmeapples - do we have an API for filtering by task queue?
