### ISSUE TITLE
Temporal web interrupted by request to /health endpoint

### ISSUE THREAD

**Issue by pauldemarco** [temporalio/web#275]
## Expected Behavior
The website should be unaffected by other concurrent requests.

## Actual Behavior
If kubernetes fires a GET request at the /health endpoint, any action the user is doing on the website will get interrupted.

**Comment by wxing1292** [comment]
synced with @feedmeapples 

seems that web does not have a health endpoint
frontend's health check is shallow, i.e. only accessing in mem variable

close the issue for now.

if issue still relevant, plz reopen
