### ISSUE TITLE
Surface in UI status of cron run

### ISSUE THREAD

**Issue by mfateev** [temporalio/web#29]
Currently cron workflows are presented as multiple runs with continued_as_new status even if run has failed. It is because cron is implemented as a serie of workflow runs that call continue as new and the result of the run is included into [WorkflowExecutionContinuedAsNew](https://github.com/temporalio/temporal-proto/blob/0f6dd9f1944376b1a3dcf35147a7fd362ee7b517/event/message.proto#L94) event.

Ideally we want to show the actual status in the list view and the details view as well.

**Comment by sw-yx** [comment]
some ambiguity here - what is considered the "actual status" of the cron workflow - the last run? the status of all the runs? need to enumerate the cases here and repro
