### ISSUE TITLE
[Bug] Version upgrade prompt banner is present on latest version

### ISSUE THREAD

**Issue by robzienert** [temporalio/web#316]
**Describe the bug**

I'm on 1.9.0, the latest current version, but the "new version" banner is still there. I would expect it to not be there. 
Clicking on the banner, I'm taken to the 1.8.1 release page.

**Expected behavior**

I would not expect the banner to be present if I'm on the latest version.

**Desktop (please complete the following information where relevant):**
 - OS: [e.g. iOS] OSX
 - Browser [e.g. Chrome, Safari] Chroe
 - Temporal Web Version [e.g. 1.7?] 1.9.0
 - Tctl Version [e.g. 1.7?] NA
 - are you using Docker or building from source? Docker

**Comment by sw-yx** [comment]
received and discussing now, thanks Rob

**Comment by feedmeapples** [comment]
i've updated the version info announcement to include v1.9.0. Also separately looking into why newer version may show announcement for older versions

**Comment by sw-yx** [comment]
hey Rob, we think we have fixed this for the time being, please let us know if the problem still persists!

**Comment by GreyTeardrop** [comment]
Hey guys, I think I have the same issue. I'm running server 1.9.2 and web 1.9.1 and see "A new release is available" banner pointing me to the [1.9.0](https://github.com/temporalio/temporal/releases/tag/v1.9.0) server version.
