### ISSUE TITLE
[Feedback] Thank you for the recent enhancement in temporal web 1.9.0 where workflow Input now shows in JSON format.

### ISSUE THREAD

**Issue by ShubhSingh** [temporalio/web#333]
> Your feedback here!

Thank you temporal web for the recent enhancement in temporal web 1.9.0 where workflow Input now shows in JSON format.
Since earlier Input was just a plain text it was difficult to use this input in case you want to resubmit workflow from tctl.
Now with JSON we can quickly copy the input & resubmit a workflow from tctl.
Also it's easier to read each Input property more clearly.
Thank you team and keep up the good work. :relaxed:

PS: Raised a small bug as well here:
https://github.com/temporalio/web/issues/332
:grin:

**Comment by sw-yx** [comment]
i think this one is all credit to @feedmeapples  :) https://github.com/temporalio/web/pull/309

**Comment by feedmeapples** [comment]
@ShubhSingh wow we appreciate the feedback, thank you!
