### ISSUE TITLE
[Feature Request] Configuration option for disabling terminate workflow button

### ISSUE THREAD

**Issue by jeffschoner-stripe** [temporalio/web#335]
**Is your feature request related to a problem? Please describe.**
It is easy to accidentally terminate the wrong workflow with the 'Terminate' button that is in the upper right hand corner of the summary page for a workflow. This appears to be the only operation on temporal-web that is not read-only. In a Temporal deployment shared by multiple teams, ensuring the interface is read-only reduces the risk that somebody will accidentally or intentionally affect other teams' workflows.

**Describe the solution you'd like**
Add an option to `config.yml` to remove this button. Something like,
```
disable_terminate: true
```

**Comment by feedmeapples** [comment]
@jeffschoner-stripe thx for suggestion about the config.yml

Before the config.yml file existed, we've added such config as an env variable `TEMPORAL_PERMIT_WRITE_API` https://github.com/temporalio/web#configuration

Let me know if this unblocks you

**Comment by jeffschoner-stripe** [comment]
@feedmeapples Yes, I believe it should unblock us. I overlooked that setting reading through the docs earlier.
