### ISSUE TITLE
[Bug] Unusual whitespace in web ui

### ISSUE THREAD

**Issue by paymog** [temporalio/web#349]
**Describe the bug**
Sometimes the web UI has an lots of unusual whitespace

![image](https://user-images.githubusercontent.com/1986950/122289390-aad41300-cec0-11eb-82d6-be3d519e4641.png)

**To Reproduce**
Don't know how to reproduce

**Expected behavior**
I expect there to be no unusual whitespace

**Screenshots**
See above

**Desktop (please complete the following information where relevant):**
 - OS: macos
 - Browser Brave
 - Temporal Web Version 1.8.1
 - Tctl Version unknown
 - are you using Docker or building from source? docker

**Additional context**

**Comment by feedmeapples** [comment]
@paymog thanks for opening. This issue was fixed in later releases, please consider upgrading the web image to versions v1.9.1 or above
