### ISSUE TITLE
Fix workflow history json (displayed and exported) to work with Java SDK WorkflowReplayer 

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/web#350]
Currently the workflow history JSON from Web UI cannot be uses as-is for workflow replay using https://github.com/temporalio/sdk-java/blob/master/temporal-testing/src/main/java/io/temporal/testing/WorkflowReplayer.java

Here https://raw.githubusercontent.com/tsurdilo/temporal-patient-onboarding/main/onboarding-app/src/test/resources/onboardingrunhistory.json 
you can find a working JSON, 
main difference are the event names, for example:

"eventType": "EVENT_TYPE_WORKFLOW_EXECUTION_STARTED",

instead of 

"eventType": "WORKFLOW_EXECUTION_STARTED",

which creates errors with WorkflowReplayer

**Comment by tsurdilo** [comment]
Duplicate of https://github.com/temporalio/web/issues/268 that was closed by bot action.
This is still outstanding issue. I can help reproduce if needed, just let me know.

**Comment by GreyTeardrop** [comment]
👍 from me. I would love to use workflow history fetched via web and/or CLI in the Java SDK.

I wonder if it makes sense to have this ticket on the core repo? It looks like every client library (Go, Node, Java) has a slightly different way to serialize history as JSON. A shared format would be really great (and could probably help down the road if a RESTful server API would be exposed).

**Comment by feedmeapples** [comment]
We plan to have better architecture for Web v2 that should allow exporting workflow history as JSON that accurately follows the API data model. As for the current Web v1 there are both architecturally and afaik `node-grpc` driven inaccuracies that result in such json
Currently no plans for web v1 to fix this, though for web v2 planning to have much better json view/exporting support

cc @stevekinney @sw-yx

**Comment by sw-yx** [comment]
perhaps in the meantime we should suggest to our users to use `tctl` where the export format is replayable.

**Comment by GreyTeardrop** [comment]
@sw-yx Based on my experience, Java SDK does not support the history format generated by `tctl` either.

**Comment by tsurdilo** [comment]
tctl output only works for go sdk, not for java
for java sdk neither options work without manual changes

**Comment by tsurdilo** [comment]
here is a small class that temporarily fixes the issue with Java SDK and json history output of tctl:

https://github.com/tsurdilo/java-sdk-replayer-json/blob/main/src/main/java/io/temporal/utils/PathHistory.java

you can just copy that class to your code and use it with:

      WorkflowReplayer.replayWorkflowExecution(PathHistory.replace("originalJsonHistory"));

**Comment by feedmeapples** [comment]
Created PR ^ that should fix the exported JSON for Go SDK replayer (tested using this fixture https://github.com/temporalio/samples-go/pull/136)

**Java SDK**
@Spikhalskiy is working to aligning Java SDK replayer so that it understands the same JSON as Go SDK
