### ISSUE TITLE
[Bug] TEMPORAL_ROOT_WEB_PATH does not work

### ISSUE THREAD

**Issue by czare1** [temporalio/web#354]
**Describe the bug**
Setting TEMPORAL_ROOT_WEB_PATH environment in docker-compose.yml does not work.

**To Reproduce**
1. Get docker compose file for running temporal
2. Set `TEMPORAL_WEB_ROOT_PATH=/temporal2web/` for temporal-web
3. Start all services by running docker-compose up -d
4. Open http://localhost:8088/temporal2web/ in a browser
5. 404 is returned

**Expected behavior**
Application works.

**Desktop (please complete the following information where relevant):**
 - OS: macOS
 - Browser: Chrome
 - Temporal Web Version 1.10.0
 - are you using Docker or building from source? Using docker (v1.10.0)

**Additional context**

**Comment by feedmeapples** [comment]
hello @czare1 
As this feature currently uses webpack it also requires to build your own image from source code with the environment variable set. We might improve this in web-v2, currently though it will require you to build

If that's good with you, you can look into the Dockerfile and find commented out samples of setting TEMPORAL_ROOT_WEB_PATH: https://github.com/temporalio/web/blob/master/Dockerfile#L16 and L29

to build you can do the following steps
1. clone the repo
```bash
git clone git@github.com:temporalio/web.git temporal-web
```
2. Set both lines of TEMPORAL_ROOT_WEB_PATH in Dockerfile. The file contains samples that you can uncomment

3. Build
```bash
cd temporal-web
make
docker build -t tweb/custom-root-path:1.10.0 .
```
