### ISSUE TITLE
Temporal web should refresh TLS cert in background

### ISSUE THREAD

**Issue by rfwagner** [temporalio/web#358]
The Temporal server code recently incorporated a feature where it reloads its TLS certs in the background. This is a key feature for operators running Temporal on infrastructure where server certs are rotated on a regular basis. If the code doesn't refresh in the background, the operator has to restart apps on a regular basis to avoid presenting expired server certs.

The Temporal web code should do the same.

**Comment by feedmeapples** [comment]
taking on this feature now, thanks for filing!
