### ISSUE TITLE
[Bug] WEB UI not showing workflows 'correct'

### ISSUE THREAD

**Issue by WLagemaat** [temporalio/web#361]
The flows are getting pushed out of the view in the dashboard.
Its a pure visual bug.
Every time i scroll down in the dashboard viewer, the loader pushes all records further down out the screen again.

**To Reproduce**
Steps to reproduce the behavior: difficult, it only happens on 1 of the 3 environments
1. Go to 'namespace workflow list'
2. See picture_1
![image](https://user-images.githubusercontent.com/14872534/125788824-0f3a405c-d797-486b-8a37-76a178e97653.png)

**Expected behavior**
To be on top of the dashboard.

![image](https://user-images.githubusercontent.com/14872534/125789106-5aec570d-f657-431a-9869-cb60a262d091.png)

**Desktop (please complete the following information where relevant):**
 - OS: Windows 10
 - Browser Chrome/Firefox and Edge
 - Temporal Web Version [1.9.0]
 - Tctl Version [1.9.0]
 - docker-compose is used

**Comment by bbottema** [comment]
Yup we have this too and in various browsers.

**Comment by WLagemaat** [comment]
addition: Happens only when there is a "RUNNING"  flow, if there isnt a running flow. it works as should

**Comment by feedmeapples** [comment]
@WLagemaat @bbottema this issue was fixed in v1.9.1 of Web UI. Web UI can be upgraded on its own without the server, at least up to version v1.10.0 as of time of writing

**Comment by WLagemaat** [comment]
Cheers @feedmeapples 
I'll go ahead and update to the latest (possible) then.

**Comment by WLagemaat** [comment]
Updating to 1.10.0 fixed the issue for me. thx for pointing out @feedmeapples
