### ISSUE TITLE
[Feature Request] Support multiple json-like encodings for display

### ISSUE THREAD

**Issue by skrul** [temporalio/web#376]
**Is your feature request related to a problem? Please describe.**

We have a situation where we use a custom data converter to sometimes encode using Jackson and sometimes encode using Gson. For this to work, we have to use two encoding types even though both encoders produce JSON. Temporal Web will only display the encoding type "json/plain" (well also protobuf...) and everything else is shown as base64. 

**Describe the solution you'd like**

Perhaps a way to configure a list of encodings to treat at json or generally better support for plugging in decoders in web.

**Comment by feedmeapples** [comment]
@skrul would like to understand better

Are you using data converter interface to encode payloads? If so, have you also tried enabling decryption of payloads for UI using `tctl dataconverter web  --web_ui_url <url>` ?

**Comment by skrul** [comment]
@feedmeapples This may be a newer feature, I'm still using 1.8. I don't see any docs for `tctl dataconverter` on temporal.io... but perhaps this is a way for tctl and the web UI to leverage a temporal worker to decode a payload for non-standard encoding types? that would be nice!

**Comment by feedmeapples** [comment]
@skrul yes it's a newer feature and seems it's not yet described in the docs. I'll communicate with our docs team to see if this can be prioritized

Meanwhile you can look at this go example on how to convert payloads https://github.com/temporalio/samples-go/tree/master/cryptconverter

Then you can use tctl to enable the decryption for the Web UI using 
```shellscript
tctl dataconverter web --web_ui_url <url>
```
And following the link that tctl outputs. Following the link will let the WebUI know that the payloads need to be decrypted and it will communicate to tctl's data converter for decryption
