### ISSUE TITLE
[Feature Request] Publish NPM Package

### ISSUE THREAD

**Issue by bouk** [temporalio/web#385]
**Is your feature request related to a problem? Please describe.**

Hello, I'd like to run the Temporal web UI locally outside of Docker. I can do this by cloning the package and running `npm run dev`, but I was wondering if you could provide an NPM package with release builds.

**Describe the solution you'd like**

I'd like to do `npm install -g @temporalio/web` and then be able to run `temporal-web` directly.

**Comment by feedmeapples** [comment]
do you want to use specifically npm, or just to remove docker part?

If latter, will running a binary instead of npm package work for you? We are planning to have a binary available with the next version of ui:
https://github.com/temporalio/ui-server
http://github.com/temporalio/ui

**Comment by bouk** [comment]
Oh that's even better! Hadn't seen that, thank you.
