### ISSUE TITLE
[Feature Request] Case Insensitive & Partial Match Search [by Workflow Name]

### ISSUE THREAD

**Issue by rupalivohra** [temporalio/web#403]
**Is your feature request related to a problem? Please describe.**
I'm frustrated when I can't find a workflow by the name because I haven't entered the full text of the workflow name, or because my search uses lowercase letters when the name has uppercase letters.

**Describe the solution you'd like**
It'd be great if I could search "load" for "load_tracking" and see the matching workflows:
Current:
![Screen Shot 2021-10-20 at 1 30 26 PM](https://user-images.githubusercontent.com/5040637/138167535-f5c7ca3f-b5fe-471e-9f7f-f64bd094ec88.png)
![Screen Shot 2021-10-20 at 1 30 51 PM](https://user-images.githubusercontent.com/5040637/138167601-e3a49792-9d0d-4956-9773-2afdd3dffec8.png)

Desired:
![partial](https://user-images.githubusercontent.com/5040637/138167506-1e614c9d-e2a7-4caf-b0ce-ba99706b0f8e.png)
![casing](https://user-images.githubusercontent.com/5040637/138167623-80e2260b-a99f-4584-a5ae-300e33546e5c.png)

**Additional context**
I know my screenshot of the casing is the opposite of what I described; either way, I think the case-insensitivity would be great to support.

**Comment by feedmeapples** [comment]
hi @rupalivohra currently there is a limitation in the API as both Workflow ID and Run ID are keywords in the DB and only support searching by exact match

afaik the only option to filter by a loose match is to set a search attribute with Workflow ID and Run ID values and then use query syntax to filter the workflows https://docs.temporal.io/docs/content/what-is-a-search-attribute/

**Comment by rupalivohra** [comment]
@feedmeapples - To confirm - will leveraging `tctl` to add workflowName as custom search attributes as described [here](https://docs.temporal.io/docs/content/what-is-a-search-attribute/#custom-search-attributes) allow me to search for case-insensitive and partial string matches of my workflows in the Temporal UI?

`tctl admin cluster add-search-attributes --name WorkflowName --type String`

**Comment by feedmeapples** [comment]
@rupalivohra that's correct

Then you can use a query similar to `CustomStringField like "mywork"`

![image](https://user-images.githubusercontent.com/11838981/140408009-f6c73f33-b192-4cdf-abb7-2a7357c6c566.png)
