### ISSUE TITLE
[Feature Request] Provide arm64 builds for dockerhub

### ISSUE THREAD

**Issue by jenskueper** [temporalio/web#420]
**Is your feature request related to a problem? Please describe.**
ARM becomes more and more popular with things like Apple M1 and AWS Graviton. Temporal itself is already available as arm64 image, but temporal web is not.

**Describe the solution you'd like**
I haven't found the build/publish pipeline for temporal web but since its based on none, multiarch builds should be realatively easy. Happy to help out if somebody can give me a hint where to start.

**Comment by APTy** [comment]
+1, also hoping for an arm64 build!

**Comment by feedmeapples** [comment]
hello, we now provide arm64 builds for our new UI https://hub.docker.com/r/temporalio/ui/tags

https://github.com/temporalio/ui
https://github.com/temporalio/ui-server
