### ISSUE TITLE
[Feature Request] Binary file with pkg or etc.

### ISSUE THREAD

**Issue by abserari** [temporalio/web#432]
**Is your feature request related to a problem? Please describe.**
When I have an environment that has no node or docker. I want to pre-built binary to run temporal-web

**Describe the solution you'd like**
According to the search results, it seems possible to use pkg or some else tools to help with pre-build.

**Additional context**
https://github.com/vercel/pkg

**Comment by feedmeapples** [comment]
hey @abserari 

our new version of the UI can be built into a binary https://github.com/temporalio/ui-server . It's currently in beta

It's also built into a temporalite which is useful at development https://github.com/DataDog/temporalite
