### ISSUE TITLE
Add support for multiple service backends

### ISSUE THREAD

**Issue by mfateev** [temporalio/web#47]
Currently when running multiple temporal service clusters each of them has to have its own web UI instance. Consider supporting more than one cluster from a single UI instance.

**Comment by linvon** [comment]
This is very urgent

**Comment by feedmeapples** [comment]
@linvon the current plan is to implement this feature post-v1. If anything pls feel free to elaborate, i can keep you updated on this feature

**Comment by sw-yx** [comment]
@linvon would like to know more about your usecase and why it is so important to you. if you would like to chat you can contact me at swyx@temporal.io. We don't currently have an ETA on this feature.
