### ISSUE TITLE
Add Namespace overview stats

### ISSUE THREAD

**Issue by antstorm** [temporalio/web#49]
Hi 👋 

I think it would be super handy to display some stats for the selected namespace in the Web UI for a quick overview of:

- total running workflows
- total failed / timed out workflows
- longest running workflows 
- workflow throughput

all split by workflow names if possible

**Comment by feedmeapples** [comment]
For visibility, this will be taken care of in post-v1, will keep you updated! Thanks for opening the ticket

**Comment by sw-yx** [comment]
still important to us, just low pri, appreciate the feature request
