### ISSUE TITLE
Improve spin up time & resources usage

### ISSUE THREAD

**Issue by feedmeapples** [temporalio/web#50]
- webpack creates a single .js bundle totaling 3.8mb. This slows down the initial page load
- webpack does too many things on initial production load, that should've been done on the image build step. As reported "the following log line on startup: temporal-web_1  | ℹ ｢wdm｣: wait until bundle finished: /. "
- possibly switch to newer versions of webpack from v.3

**Comment by feedmeapples** [comment]
The spin up time was addressed in https://github.com/temporalio/web/pull/77

**Comment by ringods** [comment]
Why are you running webpack in the container? Wouldn't it be better to let webpack run on your CI build system and copy the built artifacts into the container image as static files?

**Comment by feedmeapples** [comment]
@ringods it doesn't run webpack in container starting v0.27. Both start up time and resources usage were addressed
