### ISSUE TITLE
[Feature Request] Provide arm64 builds for temporalio/web dickerhub

### ISSUE THREAD

**Issue by vishnu-anil** [temporalio/web#503]
**Is your feature request related to a problem? Please describe.**
Yes I am unable to run temporal web in my aws graviton instances as they need to be arm64 arch based

**Describe the solution you'd like**
I would like to have support for temporalio/web with arm64 architecture builds

**Additional context**

**Comment by vishnu-anil** [comment]
I did try to build your Dockerfile for web with buildx, but that does not work. Seems like some of the node modules do not support arm64 platform. Please look into this on priority

**Comment by feedmeapples** [comment]
sorry for the late reply, we provide arm build of UI v2 https://hub.docker.com/layers/temporalio/ui/2.6.2/images/sha256-2d9b88a0533d67e31b2ec1e8d3b0ad83098281ecf1e00b4c260485698179a21a?context=explore
